### PR TITLE
Worked on Quote Generator Project

### PR DESCRIPTION
**Pull request by subham-04**
Through this project, I came across a various new concept

### CODE REVIEW

**Comment by subham-04** [comment]
where should I change? can you please guide me sir?

**Comment by subham-04** [comment]
> Hi @subham-04 , great work you got there. Please add your work below the last contribution to the quote generator

where should I change? can you please guide me sir?

**Comment by donmarvex** [comment]
> > Hi @subham-04 , great work you got there. Please add your work below the last contribution to the quote generator
> 
> where should I change? can you please guide me sir?

You are required to add your links to the bottom of the quote generator list just below the last contributors work. Submissions are added chronologically, so older contributions appear up top and recent ones below

**Review by donmarvex — APPROVED** [review]

**Comment by donmarvex** [comment]
> Definitely sir

Thank You. Also since your last commit there have been changes in the remote repository, so please resolve the merge conflict and we can merge away!

**Comment by subham-04** [comment]
How do I resolve these conflict, sir? can you please help me, sir?

**Pull request closed without merging**
