### PR TITLE
Request add to the students list

### PR DESCRIPTION
**Pull request by jthinlay**
Completed the first two projects and want to add them to the list.

### CODE REVIEW

**Comment by jthinlay** [comment]
added first two projects to the list.

**Comment by jthinlay** [comment]
Added my four more projects on the list.

**Comment by jthinlay** [comment]
Request to merge

**Comment by MattCSmith** [comment]
Closing due to conflicts and files that should not be present. 
Please link to your projects in your own repos in the readme file. 
Thanks 🙂

**Pull request closed without merging**
